var hierarchy =
[
    [ "jdo.Cesta", "classjdo_1_1_cesta.html", null ],
    [ "sa02.CestaResorceTest", "classsa02_1_1_cesta_resorce_test.html", null ],
    [ "sa02.CestaResource", "classsa02_1_1_cesta_resource.html", null ],
    [ "jdo.CestaTest", "classjdo_1_1_cesta_test.html", null ],
    [ "jdo.Cupon", "classjdo_1_1_cupon.html", null ],
    [ "jdo.CuponTest", "classjdo_1_1_cupon_test.html", null ],
    [ "categories.GuiTest", "interfacecategories_1_1_gui_test.html", null ],
    [ "categories.IntegrationTest", "interfacecategories_1_1_integration_test.html", null ],
    [ "jdo.Mail", "classjdo_1_1_mail.html", null ],
    [ "sa02.Main", "classsa02_1_1_main.html", null ],
    [ "sa02.MandarMail", "classsa02_1_1_mandar_mail.html", null ],
    [ "sa02.MyResource", "classsa02_1_1_my_resource.html", null ],
    [ "sa02.PagosResorceTest", "classsa02_1_1_pagos_resorce_test.html", null ],
    [ "sa02.PagosResource", "classsa02_1_1_pagos_resource.html", null ],
    [ "jdo.Paypal", "classjdo_1_1_paypal.html", null ],
    [ "jdo.PayPalTest", "classjdo_1_1_pay_pal_test.html", null ],
    [ "jdo.Pedido", "classjdo_1_1_pedido.html", null ],
    [ "jdo.PedidoTest", "classjdo_1_1_pedido_test.html", null ],
    [ "util.PreparaDatos", "classutil_1_1_prepara_datos.html", null ],
    [ "jdo.Producto", "classjdo_1_1_producto.html", null ],
    [ "sa02.ProductosResource", "classsa02_1_1_productos_resource.html", null ],
    [ "sa02.ProductosResourceTest", "classsa02_1_1_productos_resource_test.html", null ],
    [ "jdo.ProductoTest", "classjdo_1_1_producto_test.html", null ],
    [ "jdo.Resenya", "classjdo_1_1_resenya.html", null ],
    [ "sa02.ResenyaResource", "classsa02_1_1_resenya_resource.html", null ],
    [ "sa02.ResenyaResourceTest", "classsa02_1_1_resenya_resource_test.html", null ],
    [ "jdo.ResenyaTest", "classjdo_1_1_resenya_test.html", null ],
    [ "Runnable", null, [
      [ "gui.Loading.Hilo", "classgui_1_1_loading_1_1_hilo.html", null ],
      [ "gui.VentanaCrearCuenta.Hilo", "classgui_1_1_ventana_crear_cuenta_1_1_hilo.html", null ]
    ] ],
    [ "jdo.Usuario", "classjdo_1_1_usuario.html", null ],
    [ "sa02.UsuariosResource", "classsa02_1_1_usuarios_resource.html", null ],
    [ "sa02.UsuariosResourceTest", "classsa02_1_1_usuarios_resource_test.html", null ],
    [ "jdo.UsuarioTest", "classjdo_1_1_usuario_test.html", null ],
    [ "gui.VentanaAnadirProductoTest", "classgui_1_1_ventana_anadir_producto_test.html", null ],
    [ "gui.VentanaBusquedaTest", "classgui_1_1_ventana_busqueda_test.html", null ],
    [ "gui.VentanaLoginTest", "classgui_1_1_ventana_login_test.html", null ],
    [ "gui.VentanaVentaProductosTest", "classgui_1_1_ventana_venta_productos_test.html", null ],
    [ "gui.VentanaVerificarCodigoTest", "classgui_1_1_ventana_verificar_codigo_test.html", null ],
    [ "jdo.VentaProducto", "classjdo_1_1_venta_producto.html", null ],
    [ "sa02.VentaProductoResource", "classsa02_1_1_venta_producto_resource.html", null ],
    [ "sa02.ventaProductosResource", "classsa02_1_1venta_productos_resource.html", null ],
    [ "jdo.VentaProductoTest", "classjdo_1_1_venta_producto_test.html", null ],
    [ "jdo.Visa", "classjdo_1_1_visa.html", null ],
    [ "jdo.VisaTest", "classjdo_1_1_visa_test.html", null ],
    [ "JFrame", null, [
      [ "gui.Loading", "classgui_1_1_loading.html", null ],
      [ "gui.VentanaAdmin", "classgui_1_1_ventana_admin.html", null ],
      [ "gui.VentanaAnadirProducto", "classgui_1_1_ventana_anadir_producto.html", null ],
      [ "gui.VentanaBusqueda", "classgui_1_1_ventana_busqueda.html", null ],
      [ "gui.VentanaBusqueda2", "classgui_1_1_ventana_busqueda2.html", null ],
      [ "gui.VentanaCesta", "classgui_1_1_ventana_cesta.html", null ],
      [ "gui.VentanaCompras", "classgui_1_1_ventana_compras.html", null ],
      [ "gui.VentanaCrearCuenta", "classgui_1_1_ventana_crear_cuenta.html", null ],
      [ "gui.VentanaLogin", "classgui_1_1_ventana_login.html", null ],
      [ "gui.VentanaNumVentas", "classgui_1_1_ventana_num_ventas.html", null ],
      [ "gui.VentanaOpcion", "classgui_1_1_ventana_opcion.html", null ],
      [ "gui.VentanaPago", "classgui_1_1_ventana_pago.html", null ],
      [ "gui.VentanaResenya", "classgui_1_1_ventana_resenya.html", null ],
      [ "gui.VentanaVentaProductos", "classgui_1_1_ventana_venta_productos.html", null ],
      [ "gui.VentanaVerificarCodigo", "classgui_1_1_ventana_verificar_codigo.html", null ]
    ] ]
];