name: Java CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:5.7
        env:
          DB_ALLOW_EMPTY_PASSWORD: yes
          DB_DATABASE: productosDB
          DB_USER: spq
          DB_PASSWORD: 'spq'
          DB_HOST: localhost
        ports: 
          - 3306:3306


    steps:
      - uses: actions/checkout@v2
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE productosDB;' -uspq -pspq
          mysql -e 'GRANT ALL ON productosDB.* TO 'spq'@'localhost';' -uspq -pspq
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
        
